export const siteConfig = {
  name: 'Antalya Yamaç Paraşütü',
  brandName: 'Antalya Yamaç Paraşütü - Mehmet Bayraktar',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://yamac.vercel.app',
  whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER || '905079046446',
  phone: process.env.NEXT_PUBLIC_PHONE || '0507 904 64 46',
  email: process.env.NEXT_PUBLIC_EMAIL || 'ymcbayraktar@gmail.com',
  address: 'Konyaaltı Varyant Seyir Terası, Muratpaşa / Antalya',
  coordinates: {
    lat: 36.8769,
    lng: 30.6525,
  },
  social: {
    instagram: 'https://www.instagram.com/antalya_yamac_parasutu/',
    youtube: '',
    googleMaps: 'https://maps.google.com/?q=36.8769,30.6525',
  },
  pilot: {
    name: 'Mehmet BAYRAKTAR',
    experienceYears: 23,
    totalFlights: '10.000+',
    origin: 'Deneyimli Ölüdeniz Pilotu',
    certification: 'THSF & FAI T2 Commercial Tandem Pilot (Lisans No: 1019)',
    issueDate: '01.04.2024',
  },
  flightInfo: {
    ageRange: '5 - 90 Yaş (Sağlıklı Herkes İçin)',
    maxWeight: '100 kg (Uygun rüzgarda 105 kg)',
    flightHours: 'Her gün 12:00 - 18:00 (Hava durumuna bağlı)',
    duration: '15 - 20 Dakika',
    mediaIncluded: 'Fotoğraf ve 4K Video Çekimleri Dahildir',
    takeoffLocation: 'Konyaaltı Varyant Seyir Terası',
    landingLocation: 'Hava durumuna göre Kalkış Alanına veya Konyaaltı Plajına İniş',
    sunglassesNote: 'Güneş gözlüğü fotoğraflarda gözlerin kısık çıkmaması ve rüzgardan korunmak için tavsiye edilir.',
    equipmentNote: 'Uluslararası test raporlu, periyodik bakımlı yedek paraşütlü tandem ekipmanlar.',
  },
  defaultLocale: 'tr' as const,
} as const;